name: Publish JordiAragonZaragoza.SharedKernel to Nuget.org

on:
  push:
    branches: [ release ]
    tags:
    - 'v*'  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --no-restore

    - name: Get version
      id: version
      uses: battila7/get-version-action@v2.2.1

    - name: Publish JordiAragonZaragoza.SharedKernel to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/JordiAragonZaragoza.SharedKernel/JordiAragonZaragoza.SharedKernel.csproj --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output nuget
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Publish JordiAragonZaragoza.SharedKernel.Application to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/JordiAragonZaragoza.SharedKernel.Application/JordiAragonZaragoza.SharedKernel.Application.csproj --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output nuget
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Publish JordiAragonZaragoza.SharedKernel.Application.Contracts to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/JordiAragonZaragoza.SharedKernel.Application.Contracts/JordiAragonZaragoza.SharedKernel.Application.Contracts.csproj --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output nuget
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Publish JordiAragonZaragoza.SharedKernel.Application.Contracts.IntegrationMessages to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/JordiAragonZaragoza.SharedKernel.Application.Contracts.IntegrationMessages/JordiAragonZaragoza.SharedKernel.Application.Contracts.IntegrationMessages.csproj --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output nuget
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Publish JordiAragonZaragoza.SharedKernel.Contracts to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/JordiAragonZaragoza.SharedKernel.Contracts/JordiAragonZaragoza.SharedKernel.Contracts.csproj --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output nuget
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Publish JordiAragonZaragoza.SharedKernel.Domain to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/JordiAragonZaragoza.SharedKernel.Domain/JordiAragonZaragoza.SharedKernel.Domain.csproj --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output nuget
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Publish JordiAragonZaragoza.SharedKernel.Domain.Contracts to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/JordiAragonZaragoza.SharedKernel.Domain.Contracts/JordiAragonZaragoza.SharedKernel.Domain.Contracts.csproj --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output nuget
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Publish JordiAragonZaragoza.SharedKernel.Infrastructure to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/JordiAragonZaragoza.SharedKernel.Infrastructure/JordiAragonZaragoza.SharedKernel.Infrastructure.csproj --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output nuget
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Publish JordiAragonZaragoza.SharedKernel.Infrastructure.EntityFramework to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/JordiAragonZaragoza.SharedKernel.Infrastructure.EntityFramework/JordiAragonZaragoza.SharedKernel.Infrastructure.EntityFramework.csproj --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output nuget
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Publish JordiAragonZaragoza.SharedKernel.Infrastructure.EventStore to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/JordiAragonZaragoza.SharedKernel.Infrastructure.EventStore/JordiAragonZaragoza.SharedKernel.Infrastructure.EventStore.csproj --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output nuget
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Publish JordiAragonZaragoza.SharedKernel.Presentation.HttpRestfulApi to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/JordiAragonZaragoza.SharedKernel.Presentation.HttpRestfulApi/JordiAragonZaragoza.SharedKernel.Presentation.HttpRestfulApi.csproj --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output nuget
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Publish JordiAragonZaragoza.SharedKernel.Presentation.HttpRestfulApi.Contracts to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/JordiAragonZaragoza.SharedKernel.Presentation.HttpRestfulApi.Contracts/JordiAragonZaragoza.SharedKernel.Presentation.HttpRestfulApi.Contracts.csproj --configuration Release -p:PackageVersion=${{steps.version.outputs.version-without-v}} --output nuget
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json